
###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "6745d7a8d0524dbda22ba039",
    "content": "This is a comment.",
    "author": "John Doe"
}

###

GET http://localhost:3000/comments/67434458681059c44c2af555

###

PUT http://localhost:3000/comments/67434458681059c44c2af555
Content-Type: application/json

{
    "content": "Update Comment"
}

###

DELETE  http://localhost:3000/comments/67434458681059c44c2af555

###

GET http://localhost:3000/comments/post/6745d7a8d0524dbda22ba039